# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce656edd15621bfa604e448703baa15b2d369205cca0c971c305c812606068eeeb0ff1696802a7cdfe0d377996297cfbfe6329badb2dcd8258caa1f08950abbd

test:
  secret_key_base: f1a14eee8dfc5731f359cb5aaad51ce070b5f2ce15c6b9d59d6dbf463678d9d3ff2ea3dfd635a5265e19c715418e1784c7db5db23216d65a32d7bee486fdc80a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
